// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiRRhvnw3ph9GbFsilM4GJQxOkLxKZlY8',
    appId: '1:373125623062:web:ac4cee4584723dd4807437',
    messagingSenderId: '373125623062',
    projectId: 'modelday-d4781',
    authDomain: 'modelday-d4781.firebaseapp.com',
    storageBucket: 'modelday-d4781.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu-znUpC-0JYBzRzYdBLK0GSpqbTXSCc',
    appId: '1:373125623062:android:dc783ca61dd535d5807437',
    messagingSenderId: '373125623062',
    projectId: 'modelday-d4781',
    authDomain: 'modelday-d4781.firebaseapp.com',
    storageBucket: 'modelday-d4781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSQeppkOl2ImmPo7Xgw0wl5B0mfqwCWEA',
    appId: '1:373125623062:ios:c17c45344c8a067d807437',
    messagingSenderId: '373125623062',
    projectId: 'modelday-d4781',
    authDomain: 'modelday-d4781.firebaseapp.com',
    storageBucket: 'modelday-d4781.appspot.com',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSQeppkOl2ImmPo7Xgw0wl5B0mfqwCWEA',
    appId: '1:373125623062:ios:c17c45344c8a067d807437',
    messagingSenderId: '373125623062',
    projectId: 'modelday-d4781',
    authDomain: 'modelday-d4781.firebaseapp.com',
    storageBucket: 'modelday-d4781.appspot.com',
    iosBundleId: 'com.example.newFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiRRhvnw3ph9GbFsilM4GJQxOkLxKZlY8',
    appId: '1:373125623062:web:ac4cee4584723dd4807437',
    messagingSenderId: '373125623062',
    projectId: 'modelday-d4781',
    authDomain: 'modelday-d4781.firebaseapp.com',
    storageBucket: 'modelday-d4781.appspot.com',
  );
}
